---
management:
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always 
  endpoints: 
    web:
      exposure:
        include: "*"  

server:
    port: 8080
    error:
     include-stacktrace: never
    
logging:
     path: 
     file: 
     level: 
       root: INFO 
       org: 
        springframework: 
         security: INFO

info:
  app:
   name: "praveen-user-management-service"
   description: "Praveen User Management Service"
   version: "1.0"
   encoding: "UTF-8"
   java:
    version: "1.8"

spring:
   application:
     name: PRAVEEN-USER-MANAGEMENT-SERVICE
   profiles:
    active: dev   
   cloud:
    discovery:
     enabled: false 
    service-registry:
      auto-registration:
        enabled: false
        

   jpa:
     show-sql: true 
     database: MYSQL
     generate-ddl: true
   datasource :
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://root:password@localhost:3306/praveendb?reconnect=true
          username: root
          password: password
          hikari:
            connectionTimeout : 30000
            idleTimeout : 600000
            maxLifetime : 1800000
            maximumPoolSize : 5
            
   rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

praveen-user-management-service:
          rabbitmq:
            queueName: praveenmq
            topicExchange: praveenexchange     