---
management:
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always 
  endpoints: 
    web:
      exposure:
        include: "*"  

server:
    port: 8081
    error:
     include-stacktrace: never
    
logging:
     path: 
     file: 
     level: 
       root: INFO 
       org: 
        springframework: 
         security: INFO

info:
  app:
   name: "praveen-user-management-service"
   description: "Praveen User Management Service"
   version: "1.0"
   encoding: "UTF-8"
   java:
    version: "1.8"

spring:
   application:
     name: PRAVEEN-USER-MANAGEMENT-SERVICE

   jpa:
     show-sql: true 
     database: MYSQL
     generate-ddl: true
   datasource :
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver #org.hsqldb.jdbc.JDBCDriver
          url: jdbc:mysql://localhost/PRAVEEN-USER-MANAGEMENT-SERVICE?autoreconnect=true #jdbc:hsqldb:hsql://localhost/testdb
          username: 
          password:
          hikari:
            connectionTimeout : 30000
            idleTimeout : 600000
            maxLifetime : 1800000
            maximumPoolSize : 5
            
   rabbitmq:
    host: orangutan.rmq.cloudamqp.com
    port: 5672
    username: cuorvmqg
    password: LR7A73-8bydesk5Pp2U6Ad7mEEKtMeHX
 

praveen-user-management-service:
          rabbitmq:
            queueName: praveenmq
            topicExchange: praveenexchange
